### ISSUE TITLE
Required => false seems to be broken

### ISSUE THREAD

**Issue by gillesvandevoorde** [lecterror/cakephp-filter-plugin#18]
Hey. Thansk for the great plugin. It seems I am ot the only one who has this issue. (some others mentioned it on your blog). I'm using Cake 2.4.9

I have a field that doesn't have the issue (not required), and one that always is required. even when I add required => false.

I've tried using other settings on the field, but it remains required.

UPDATE: it seems the settings used in the model cannot be overriden.
I had:

class Post extends AppModel {
    public $validate = array(
        'title' => array(
            'rule' => 'notEmpty'
        ),
        'body' => array(
            'rule' => 'notEmpty'
        )
    );

Guess that 'solves' that.

**Comment by bancer** [comment]
Actually the issue is still valid.
```
'MyModel.my_field' => array(
    'required' => false,
),
```
does not have effect. The form field has a start and is still required.
