### ISSUE TITLE
The links in readme file are not valid anymore

### ISSUE THREAD

**Issue by bancer** [lecterror/cakephp-filter-plugin#37]
* http://lecterror.com/articles/view/cakephp-generic-filter-plugin
* http://lecterror.com/articles/view/cakephp-filter-plugin-advanced-usage

Could you move the content of these pages to wiki here? https://github.com/lecterror/cakephp-filter-plugin/wiki

**Comment by lecterror** [comment]
Done! Thanks for reminding me :)
